# Generated by Django 3.2.9 on 2022-01-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='status',
        ),
    ]
