# Generated by Django 3.2.9 on 2022-01-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
