# Generated by Django 3.2.9 on 2022-01-19 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20220119_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='docid',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
