# Generated by Django 3.2.9 on 2022-01-20 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_docid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='docid',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
