# Generated by Django 3.2.9 on 2022-01-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_docid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
