# Generated by Django 3.2.9 on 2022-01-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='lastname',
        ),
        migrations.AddField(
            model_name='doctor',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
