# Generated by Django 3.2.9 on 2022-01-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_auto_20220120_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
